version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tickets-net
  mysql-db:
    container_name: tickets-db
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tickets-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    networks:
      - tickets-net

networks:
  tickets-net: {}
